import { spawn } from "node:child_process";
import { BACKEND, MODEL, LIMITS } from "./config.mjs";

// The dose is generated by echo's own small model, never by the main agent.
// That is what makes echo agent-agnostic: the agent does not need to know it exists.

const PROMPTS = {
  youSaid: `You help a busy Chinese software engineer learn English from his own words.
He just sent the following message (in Chinese) to an AI coding agent.
Write what he said in natural, concise English, the way an engineer would say it to a colleague.
If the message is long, keep only its core point. At most 2 sentences, at most ${LIMITS.youSaidWords} words.
Output only the English. No quotes, no explanations.`,

  better: `You help a Chinese software engineer improve his English.
He wrote the following message in English (as a non-native speaker) to an AI coding agent.
Rewrite it the way a native-speaking engineer would say it, keeping the meaning and tone. Fix grammar and word choice; do not add content.
If it is already natural, return it unchanged. At most ${LIMITS.youSaidWords} words.
Output only the rewritten English. No quotes, no explanations.`,

  inShort: `You help a busy Chinese software engineer learn English while he works with AI coding agents.
Below is an agent's reply (possibly in Chinese, possibly long, possibly with code).
Say the gist of the reply in ONE plain English sentence, at most ${LIMITS.inShortWords} words, as if a colleague summarized it aloud.
Output only that sentence. No quotes, no explanations.`,
};

export function looksEnglish(text) {
  const letters = (text.match(/[A-Za-z]/g) || []).length;
  const cjk = (text.match(/[\u4e00-\u9fff]/g) || []).length;
  return letters > 0 && letters >= cjk * 3;
}

export async function dose(role, text, { level = 0 } = {}) {
  let kind;
  if (role === "user") kind = level >= 1 && looksEnglish(text) ? "better" : "youSaid";
  else kind = "inShort";
  const en = await complete(PROMPTS[kind], text);
  return { kind, en: tidy(en) };
}

function tidy(s) {
  return (s || "").trim().replace(/^["'“”]+|["'“”]+$/g, "").replace(/\s+/g, " ");
}

// Demo only: a stand-in coding agent so the web page can show a full turn without a real IDE.
const AGENT_PROMPT = `You are a senior software engineer acting as an AI coding assistant. The user is a Chinese engineer.
Reply in Chinese, concise and concrete (at most 120 Chinese characters), no markdown headings. If asked to write code, give a short snippet.`;

export function simulatedAgentReply(text) {
  return complete(AGENT_PROMPT, text).then((s) => s.trim());
}

export { PROMPTS };

// A backend spec: {type:"openai", baseUrl, apiKey, name, extra} | {type:"claude-cli", model}
export const DEFAULT_BACKEND = BACKEND === "openai"
  ? { type: "openai", baseUrl: MODEL.baseUrl, apiKey: MODEL.apiKey, name: MODEL.name, extra: MODEL.extra }
  : { type: "claude-cli", model: MODEL.claudeModel };

export async function complete(system, user, backend = DEFAULT_BACKEND) {
  if (backend.type === "openai") return completeOpenAI(system, user, backend);
  return completeClaudeCli(system, user, backend);
}

async function completeOpenAI(system, user, b) {
  const res = await fetch(`${b.baseUrl.replace(/\/$/, "")}/chat/completions`, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${b.apiKey}` },
    body: JSON.stringify({
      model: b.name,
      messages: [{ role: "system", content: system }, { role: "user", content: user }],
      temperature: 0.2,
      max_tokens: 200,
      ...(b.extra || {}),
    }),
  });
  if (!res.ok) throw new Error(`model http ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const json = await res.json();
  return json.choices?.[0]?.message?.content ?? "";
}

function completeClaudeCli(system, user, b) {
  return new Promise((resolve, reject) => {
    // Strip nested-session markers so `claude -p` runs even when echo was started from inside Claude Code.
    // ECHO_INTERNAL: echo's own hooks see it and exit, so the translation call never recurses.
    const env = { ...process.env, ECHO_INTERNAL: "1" };
    for (const k of Object.keys(env)) if (k === "CLAUDECODE" || k.startsWith("CLAUDE_CODE_ENTRYPOINT")) delete env[k];
    // --tools "": pure text completion, no tool use.
    const child = spawn("claude", ["-p", "--model", b.model, "--output-format", "text", "--tools", "", "--system-prompt", system, "--", user], {
      env, stdio: ["ignore", "pipe", "pipe"], cwd: process.env.HOME,
    });
    let out = "", err = "";
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (err += d));
    child.on("error", reject);
    child.on("close", (code) => (code === 0 ? resolve(out) : reject(new Error(`claude -p exit ${code}: ${err.slice(0, 200)}`))));
  });
}
