import fs from "node:fs";
import { spawn } from "node:child_process";
import { BACKEND, MODEL, LIMITS, PATHS } from "./config.mjs";

// The dose is generated by echo's own small model, never by the main agent.
// That is what makes echo agent-agnostic: the agent does not need to know it exists.

const PROMPTS = {
  youSaid: `You help a busy Chinese software engineer learn English from his own words.
He just sent the following message (in Chinese) to an AI coding agent.
Write what he said in natural, concise English, the way an engineer would say it to a colleague.
If the message is long, keep only its core point. At most 2 sentences, at most ${LIMITS.youSaidWords} words.
Output only the English. No quotes, no explanations.`,

  better: `You help a Chinese software engineer improve his English.
He wrote the following message in English (as a non-native speaker) to an AI coding agent.
Rewrite it the way a native-speaking engineer would say it, keeping the meaning and tone. Fix grammar and word choice; do not add content.
If it is already natural, return it unchanged. At most ${LIMITS.youSaidWords} words.
Output only the rewritten English. No quotes, no explanations.`,

  inShort: `You help a busy Chinese software engineer learn English while he works with AI coding agents.
Below is an agent's reply (possibly in Chinese, possibly long, possibly with code).
Say the gist of the reply in ONE plain English sentence, at most ${LIMITS.inShortWords} words, as if a colleague summarized it aloud.
Output only that sentence. No quotes, no explanations.`,
};

export function looksEnglish(text) {
  const letters = (text.match(/[A-Za-z]/g) || []).length;
  const cjk = (text.match(/[\u4e00-\u9fff]/g) || []).length;
  return letters > 0 && letters >= cjk * 3;
}

export async function dose(role, text, { level = 0 } = {}) {
  let kind;
  if (role === "user") kind = level >= 1 && looksEnglish(text) ? "better" : "youSaid";
  else kind = "inShort";
  const en = await complete(PROMPTS[kind], text);
  return { kind, en: tidy(en) };
}

function tidy(s) {
  return (s || "").trim().replace(/^["'“”]+|["'“”]+$/g, "").replace(/\s+/g, " ");
}

// Demo only: a stand-in coding agent so the web page can show a full turn without a real IDE.
const AGENT_PROMPT = `You are a senior software engineer acting as an AI coding assistant. The user is a Chinese engineer.
Reply in Chinese, concise and concrete (at most 120 Chinese characters), no markdown headings. If asked to write code, give a short snippet.`;

export function simulatedAgentReply(text) {
  return complete(AGENT_PROMPT, text).then((s) => s.trim());
}

export { PROMPTS };

// A backend spec: {type:"openai", baseUrl, apiKey, name, extra} | {type:"claude-cli"|"pi-cli"|"zcode-cli", model}
// Precedence: ~/.echo/config.json (set from the settings panel) > environment > claude-cli.
export const ENV_BACKEND = BACKEND === "openai"
  ? { type: "openai", baseUrl: MODEL.baseUrl, apiKey: MODEL.apiKey, name: MODEL.name, extra: MODEL.extra }
  : BACKEND === "pi-cli" ? { type: "pi-cli", model: MODEL.piModel }
  : { type: "claude-cli", model: MODEL.claudeModel };

export function currentBackend() {
  try {
    const cfg = JSON.parse(fs.readFileSync(PATHS.config, "utf8"));
    if (cfg.backend?.type) return cfg.backend;
  } catch {}
  return ENV_BACKEND;
}

export function describeBackend(b = currentBackend()) {
  return b.type === "openai" ? `${b.name}` : `${b.type.replace("-cli", "")}:${b.model}`;
}

export async function complete(system, user, backend = currentBackend()) {
  if (backend.type === "openai") return completeOpenAI(system, user, backend);
  if (backend.type === "pi-cli") return completePiCli(system, user, backend);
  if (backend.type === "zcode-cli") return completeZcodeCli(system, user, backend);
  return completeClaudeCli(system, user, backend);
}

// ZCode's bundled CLI, headless. Undocumented by Z.ai (community-verified); --mode plan = no edits/commands.
async function completeZcodeCli(system, user, b) {
  const args = ["--prompt", `${system}\n\n---\n${user}`, "--mode", "plan", "--no-color", "--json", "--cwd", process.env.HOME];
  if (b.model) args.push("--model", b.model);
  const out = await runCli("zcode", args, "zcode --prompt");
  try { const j = JSON.parse(out); return j.result ?? j.text ?? j.output ?? j.message ?? j.content ?? out; } catch { return out; }
}

function runCli(cmd, args, label) {
  return new Promise((resolve, reject) => {
    // ECHO_INTERNAL: echo's own hooks see it and exit, so the model call never recurses into echo.
    const env = { ...process.env, ECHO_INTERNAL: "1" };
    for (const k of Object.keys(env)) if (k === "CLAUDECODE" || k.startsWith("CLAUDE_CODE_ENTRYPOINT")) delete env[k];
    const child = spawn(cmd, args, { env, stdio: ["ignore", "pipe", "pipe"], cwd: process.env.HOME });
    let out = "", err = "";
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (err += d));
    child.on("error", reject);
    child.on("close", (code) => (code === 0 ? resolve(out) : reject(new Error(`${label} exit ${code}: ${err.slice(0, 200)}`))));
  });
}

// pi in print mode, stripped to a bare completion: no tools, no session, no extensions/skills/context files, thinking off.
function completePiCli(system, user, b) {
  return runCli("pi", ["-p", "--no-tools", "--no-session", "--no-extensions", "--no-skills", "--no-prompt-templates", "--no-context-files",
    "--thinking", "off", "--model", b.model, "--system-prompt", system, "--", user], "pi -p");
}

async function completeOpenAI(system, user, b) {
  if (!b.baseUrl || !b.apiKey) throw new Error("openai backend needs baseUrl and apiKey");
  const res = await fetch(`${b.baseUrl.replace(/\/$/, "")}/chat/completions`, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${b.apiKey}` },
    body: JSON.stringify({
      model: b.name,
      messages: [{ role: "system", content: system }, { role: "user", content: user }],
      temperature: 0.2,
      max_tokens: 200,
      ...(typeof b.extra === "string" ? (b.extra.trim() ? JSON.parse(b.extra) : {}) : (b.extra || {})),
    }),
  });
  if (!res.ok) throw new Error(`model http ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const json = await res.json();
  return json.choices?.[0]?.message?.content ?? "";
}

// claude in print mode; --tools "" makes it a pure text completion.
function completeClaudeCli(system, user, b) {
  return runCli("claude", ["-p", "--model", b.model, "--output-format", "text", "--tools", "", "--system-prompt", system, "--", user], "claude -p");
}
